// debug functions to make the log more readable

extern void strscat(char *, int, char *);

extern char *sGUID(GUID *);
extern char *ExplainFlags(DWORD, char *, int);
extern char *ExplainPFFlags(DWORD, char *, int);
extern char *ExplainDDSCaps(DWORD, char *, int);
extern char *ExplainDDSCaps2(DWORD, char *, int);
extern char *ExplainDDSCaps3(DWORD, char *, int);
extern char *ExplainDDSCaps4(DWORD, char *, int);
extern char *ExplainDDDCaps(DWORD, char *, int);
extern char *ExplainDDDCaps2(DWORD, char *, int);
extern char *ExplainDDPalCaps(DWORD, char *, int);
extern char *ExplainDDFXALPHACaps(DWORD, char *, int);
extern char *ExplainDDFXCaps(DWORD, char *, int);
extern char *ExplainDDCKeyCaps(DWORD, char *, int);
extern char *ExplainCoopFlags(DWORD, char *, int);
extern char *ExplainPixelFormatFlags(DWORD, char *, int);
extern char *ExplainFlipFlags(DWORD, char *, int);
extern char *ExplainBltFlags(DWORD, char *, int);
extern char *ExplainBltFastFlags(DWORD, char *, int);
extern char *ExplainCreatePaletteFlags(DWORD, char *, int);
extern char *ExplainLockFlags(DWORD, char *, int);
extern char *ExplainStyle(DWORD, char *, int);
extern char *ExplainExStyle(DWORD, char *, int);
extern char *ExplainShowCmd(int);
extern char *ExplainBltStatus(DWORD);
extern char *ExplainFlipStatus(DWORD);
extern char *ExplainDDError(DWORD);
extern char *ExplainWinMessage(DWORD);
extern char *ExplainResizing(DWORD);
extern char *ExplainDeviceCaps(DWORD);
extern char *ExplainDisplaySettingsRetcode(DWORD);
extern char *ExplainSetWindowIndex(DWORD);
extern char *ExplainColorKeyFlag(DWORD);
extern char *ExplainGUID(GUID FAR *);
extern char *ExplainROP(DWORD);
extern char *ExplainNChitTest(DWORD);
extern char *ExplainDDEnumerateFlags(DWORD, char *, int);
extern char *ExplainsSystemMetrics(DWORD);
extern char *ExplainWPFlags(DWORD, char *, int);
extern char *ExplainLoadLibFlags(DWORD, char *, int);
extern char *ExplainDevModeFields(DWORD, char *, int);
extern char *ExplainMCICommands(DWORD);
extern char *ExplainMCIFlags(DWORD, DWORD, char *, int);
extern char *ExplainRegType(DWORD);
extern char *ExplainDCType(DWORD);
extern char *ExplainPeekRemoveMsg(DWORD, char *, int);
extern char *ExplainGetDCExFlags(DWORD, char *, int);
extern char *ExplainPaletteUse(UINT);
extern char *ExplainRasterCaps(DWORD, char *, int);
extern char *ExplainD3DRenderState(DWORD);
extern char *ExplainRenderstateValue(DWORD);
extern char *ExplainWfPFlags(DWORD, char *, int);
extern char *ExplainChangeDisplaySettingsFlags(DWORD, char *, int);
extern char *ExplainDICooperativeFlags(DWORD, char *, int);
extern char *ExplainRegionType(DWORD);
extern char *ExplainPixelFormat(LPDDPIXELFORMAT, char *, int);
extern char *ExplainZBufferBitDepths(DWORD, char *, int);
extern char *GetObjectTypeStr(HDC);
extern char *ExplainD3DSurfaceFormat(DWORD);
extern char *sFourCC(DWORD);
extern char *sRIID(REFIID);
extern char *ExplainRgnType(int);
extern char *ExplainWSBFlags(DWORD, char *, int);
